kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type: LoadBalancer
  externalIPs: "ac19d6254b1ff11e88f5712eac6c1e0d-1054510617.us-east-1.elb.amazonaws.com"
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 30231

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        

